### PR TITLE
fix: enforce-repeated-arg-type-style rule finds false positives in case of invalid types

### LINKED ISSUE #1032: The `enforce-repeated-arg-type-style` rule finds some false positives.
**Describe the bug**
The `enforce-repeated-arg-type-style` rule finds some false positives. I will demonstrate this using the repository https://github.com/influxdata/telegraf (over 650k lines) as an example.

**To Reproduce**
1. I updated revive `go install github.com/mgechev/revive@latest`
2. I cloned repo and switched to particular branch
```
git clone https://github.com/influxdata/telegraf.git
cd telegraf
git checkout v1.31.3
```
3. I run it with the following flags & configuration file:
```shell
# flags
revive -config revive.toml ./... | sort
```
```toml
#revive.toml
[rule.enforce-repeated-arg-type-style]
  arguments = ["short"]
```
4. Some of the findings are false positives.

**Expected behavior**
I would like only the findings that are not false positives to be shown.

**Logs**
Some examples:

`plugins/inputs/webhooks/artifactory/artifactory_webhook.go:23:87: repeated argument type can be omitted`:
image

`plugins/outputs/bigquery/bigquery.go:244:45: repeated argument type can be omitted`:
image

`plugins/outputs/mqtt/mqtt_test.go:803:59: repeated argument type can be omitted`:
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 23:10
 - Version of Go:
```shell
$ go version 
go version go1.23.0 linux/amd64
```

### PR DESCRIPTION
**Pull request by denisvmedia**
closes #1032

### CODE REVIEW

**Comment by zak-pawel** [comment]
@denisvmedia Thanks! I tested code from this PR and it fixes most of the cases.

However, it still sees a problem for such cases (for `op`):
```
func printConfig(name string, p telegraf.PluginDescriber, op string, commented bool, di telegraf.DeprecationInfo, outputBuffer io.Writer) {
```
But when I change the second argument from `telegraf.PluginDescriber` to `int`, the function stops being problematic:
```
func printConfig(name string, p int, op string, commented bool, di telegraf.DeprecationInfo, outputBuffer io.Writer) {
```

There is a similar problem with return types.

**Comment by denisvmedia** [comment]
Yeah, that was my oversight. I will fix it. Thanks!

**Comment by denisvmedia** [comment]
@zak-pawel does it work for you now?

**Review by zak-pawel — APPROVED** [review]
Now it works very well, thanks!

**Comment by chavacava** [comment]
Hi @denisvmedia thanks for the PR, it LGTM.
Could you please add some test cases to the rule tests?

**Comment by denisvmedia** [comment]
@chavacava it's actually non-trivial to test it. We'll have to provide the means to pass fake imports in our test engine. Otherwise, any package we import won't be found and the tests will start failing. I played around with a custom (fake) importer, but I didn't have enough time to simulate the invalid package situation. I can try checking it later. Do you think we can merge this PR now without having the tests at the moment?

**Comment by chavacava** [comment]
IMO relying on actual type analysis is over-killing for such a simple rule.
I wonder if just comparing the string representation of parameters types is not enough.
A canonical string representation of parameters' types can be obtained by calling `gofmt` on each `*Field.Type` of  `FuncDecl.Type.Params.List`.

**Comment by denisvmedia** [comment]
That's what my TODO comment actually says (maybe I wasn't clear enough in it ;)). But what I wanted is to have a quick fix to make sure that this rule at least doesn't have false positives (it seems to me to be better than having false negatives), and then invest some more time to have a full fix. But if you think it makes no sense to merge it as is, I can revise the PR. I'm just not sure when I will have time to play with it.

**Pull request merged**
