### PR TITLE
WIP: replaces gcexportdata.NewImporter 

### LINKED ISSUE #713: gcexportdata.NewImporter: huge impact on performance
**Describe the bug**

`gcexportdata.Find` has been rewritten:

- https://go-review.googlesource.com/c/tools/+/310515
- https://github.com/golang/tools/commit/2a900561e78a69afe5828ff8388aeb0dfc6220dc

`gcexportdata.NewImporter` uses `gcexportdata.Find`.

And `revive` uses `gcexportdata.NewImporter`:
https://github.com/mgechev/revive/blob/60e1ae4a014ff158513922aff1597ec974945546/lint/package.go#L30

**To Reproduce**
1. update `golang.org/x/tools` to `v0.1.12-0.20220628192153-7743d1d949f1`
2. build a binary
3. clone https://github.com/kubernetes-sigs/cluster-api
4. run the binary 

**Expected behavior**
Run fast

**Logs**

-

**Desktop (please complete the following information):**
 - OS: Linux
 - Version of Go: all versions

**Additional context**

`gcexportdata.NewImporter` and `gcexportdata.Find` are now deprecated.

https://github.com/golangci/golangci-lint/issues/2997#issuecomment-1190449973

### PR DESCRIPTION
**Pull request by chavacava**
Closes #713

### CODE REVIEW

**Comment by mgechev** [comment]
Closing since looks like we fixed the issue with the default importer.

**Comment by git-hulk** [comment]
Hello @mgechev, looks the default importer can't load symbols outside the package which was mentioned in #680

**Comment by git-hulk** [comment]
> Hello @mgechev, looks the default importer still can't load symbols outside the package which was mentioned in #680. Did I miss something?

**Comment by mgechev** [comment]
@git-hulk https://github.com/mgechev/revive/pull/723 addressed https://github.com/mgechev/revive/issues/713 not #680. #680 is still open.

**Comment by git-hulk** [comment]
> @git-hulk #723 addressed #713 not #680. #680 is still open.

Thanks @mgechev

**Pull request closed without merging**
