### PR TITLE
Drop dependency on blang/semver

### PR DESCRIPTION
**Pull request by mgechev**
Fix https://github.com/mgechev/revive/issues/344.

### CODE REVIEW

**Comment by chavacava** [comment]
I will check the PR this weekend

**Comment by chavacava** [comment]
LGTM. conflicts in `go.sum` need to be resolved

**Comment by Jarema** [comment]
please reslove conflicts and merge this. It makes working with Goland in projects using revive a real pain.

**Comment by mgechev** [comment]
@Jarema available in v1.0.2.

**Pull request merged**
