### PR TITLE
Avoid false positives when returning interface values

### LINKED ISSUE #5: false positive in unexported-return
```
revive -formatter friendly github.com/cockroachdb/cockroach/pkg/...
  ⚠  unexported-return  exported func NewZeroNode returns unexported type sql.planNode, which can be annoying to use
  pkg/sql/zero.go:36:49
```
The code in question: https://github.com/cockroachdb/cockroach/blob/97c3622c2a6f4ec579ed93655b9d8a83732ac654/pkg/sql/zero.go#L36

It's true that the returned object is of an unexported type, but it is being returned as an interface, which is exported.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #5.

Please consider being a bit more patient before closing issues in the future.

### CODE REVIEW

**Comment by mgechev** [comment]
Thanks for the PR! I'll look at it the first thing in the morning tomorrow :-)

**Comment by mgechev** [comment]
The tests are passing without the fix being introduced https://github.com/mgechev/revive/pull/8

**Comment by tamird** [comment]
Thanks! The false positive I observed in CockroachDB requires this fix, so
there's something missing in the test I added.

I'll take a look at this tonight.

**Comment by tamird** [comment]
Well, I haven't been able to write a test to demonstrate the problem, but this change does fix the false positive in #5.

**Pull request merged**
