### PR TITLE
Check whether the tag name is duplicate or not

### LINKED ISSUE #705: Does it make sense to check the duplicate struct tag name?
**Is your feature request related to a problem? Please describe.**
Duplicate tag name should make no sense in the same struct and most of
cases should be mistaken, so I think we can check the struct tag.

**Describe the solution you'd like**

Check whether has the duplicate struct tag key or not

**Describe alternatives you've considered**
No

**Additional context**
No

### PR DESCRIPTION
**Pull request by git-hulk**
### CHECKLIST ###

- [x] Please, describe in details what's your motivation for this PR
- [x] Did you add tests?
- [x] Does your code follows the coding style of the rest of the repository?

This closes #705

### CODE REVIEW

**Comment by git-hulk** [comment]
> Hi @git-hulk, thanks for the PR I've made minor refactoring and added some test cases. One of the test cases fails. When a field has a tag with two keys (for example json and yaml) and these keys have the same name... the rule generates a failure (but it should not) For example, in the following struct, the rule will identify `chartName` as duplicated.
> 
> ```go
> type HelmChartArgs struct {
> 	ChartName        string                 `json:"chartName,omitempty" yaml:"chartName,omitempty"`
> }
> ```

Got it, my bad. Will fix this case.

**Comment by chavacava** [comment]
@git-hulk I've fixed a problem with the check on `protobuf` tags

**Comment by chavacava** [comment]
@git-hulk thanks for the PR

If you are motivated ... there are still some tag formats to add to the rule :)

https://github.com/golang/go/wiki/Well-known-struct-tags#list-of-well-known-struct-tags

**Comment by git-hulk** [comment]
> @git-hulk thanks for the PR
> 
> If you are motivated ... there are still some tag formats to add to the rule :)
> 
> https://github.com/golang/go/wiki/Well-known-struct-tags#list-of-well-known-struct-tags

Sure, I’ll be happy to do that

**Pull request merged**
