### PR TITLE
Add support for the new behaviour of for loops in go 1.22.

### PR DESCRIPTION
**Pull request by dominiquelefevre**
Go 1.22 has changed the behaviour of for loops. Every iteration makes new loop variables. It is now safe to take their addresses because they are guaranteed to be unique. Similarly, it is now safe to capture loop variables in functions.

### CODE REVIEW

**Comment by dominiquelefevre** [comment]
Hi, is anybody out here to take a look at the patch? @denisvmedia, @chavacava?

**Comment by chavacava** [comment]
Hi @dominiquelefevre, thanks for the PR !
I' ll try to review before the weekend.

**Comment by chavacava** [comment]
Thanks @dominiquelefevre !

**Comment by dominiquelefevre** [comment]
@chavacava could you please tag a new release so that I can make a PR to golangci-lint to use the up-to-date revive?

**Comment by ccoVeille** [comment]
Let me step out the data race fix for a moment and go back to the initial needs described in the ticket

How different is the feature brought by this PR from https://github.com/karamaru-alpha/copyloopvar created by @karamaru-alpha

And added to golangci-lint via https://github.com/golangci/golangci-lint/pull/4382

I'm glad so see it added to revive if it's the same feature but it could have consequence for copyloopvar or golangci projects maybe

**Comment by ccoVeille** [comment]
Thank you @dominiquelefevre it's way clearer now.

**Comment by ldez** [comment]
@chavacava This PR will create a performance regression because `go list` is expensive and will be called on each package.

It will be a performance regression for revive and for golangci-lint.
For golangci-lint, a way to define the Go version externally to bypass the `go list` is a solution.
I don't know enough about the revive design to propose a solution for revive.

**Comment by ldez** [comment]
Also, the implementation has a bug with Go workspaces:
```
can't parse the output of go list: invalid character '{' after top-level value
```

As a reference, a working implementation: https://github.com/golangci/modinfo/blob/main/module.go

**Comment by ldez** [comment]
I will open a dedicated issue.

**Comment by yurrriq** [comment]
This change requires `go` on the path at runtime, which should probably be noted in the README and/or release notes. I know most users will have `go` at runtime, but this effectively broke the Nix package.

> linting - retrieving failures channel: command go list: exec: "go": executable file not found in $PATH

**Comment by echoix** [comment]
> This change requires `go` on the path at runtime, which should probably be noted in the README and/or release notes. I know most users will have `go` at runtime, but this effectively broke the Nix package.
> 
> > linting - retrieving failures channel: command go list: exec: "go": executable file not found in $PATH

Ah, thanks @yurrriq for this, now I understand why the Megalinter builds (that include revive) failed when trying to update the images with a version past v1.3.7. It’s a shame that this dependency is added, it was running as an independent executable that could be copied as is in docker.

**Pull request merged**
